# Generated by Django 5.1.7 on 2025-03-20 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=15, unique=True)),
                ('numero_electeur', models.CharField(max_length=15, unique=True)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=30)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=40)),
                ('bureau_vote', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=30)),
                ('role', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parti_politique', models.TextField()),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('slogan', models.CharField(max_length=200)),
                ('site_web', models.CharField(max_length=70)),
                ('electeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='parrainage_backend.electeur')),
            ],
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parrainage', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_candidat', to='parrainage_backend.candidat')),
                ('electeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_electeur', to='parrainage_backend.electeur')),
            ],
        ),
    ]
