# Generated by Django 5.1.7 on 2025-03-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage_backend', '0002_historiqueimportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='electeur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
