# Generated by Django 5.1.7 on 2025-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage_backend', '0003_electeur_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
    ]
