# Generated by Django 5.1.7 on 2025-03-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage_backend', '0004_periodeparrainage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifParrains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parrainages_requis', models.PositiveIntegerField(default=50000)),
            ],
        ),
    ]
