# Generated by Django 5.1.7 on 2025-03-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage_backend', '0006_configuration_delete_objectifparrains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodeparrainage',
            old_name='debut',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='periodeparrainage',
            old_name='fin',
            new_name='date_fin',
        ),
        migrations.AddField(
            model_name='periodeparrainage',
            name='est_active',
            field=models.BooleanField(default=False),
        ),
    ]
